name: Django Git Actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  repository_dispatch: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install gitpython
    - name: Run Django Migrations
      run: |
        python manage.py migrate
    - name: Commit Changes to Git Repository
      run: |
        # Commit changes to the Git repository
        git config --global user.name "Viraj Khokhariya"
        git config --global user.email "vgkhokhariya@gmail.com"
        git add .
        git commit -m "Automated Commit by GitHub Actions"
    - name: Push Changes to Git Repository
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main

